force-app/main/default/objects/Modulo__c/Modulo__c.object-meta.xml
<CustomObject>
    <label>Modulo</label>
    <nameField>
        <label>modulo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modulos</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Modulo__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <summarizedField>Unidad__c.Puntos__c</summarizedField>
    <summaryForeignKey>Unidad__c.Modulo__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Modulo__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Business User</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Marketer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>App Lifecycle</fullName>
            </value>
            <value>
                <fullName>App Logic</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
            </value>
            <value>
                <fullName>Lightning</fullName>
            </value>
            <value>
                <fullName>DataManagement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Modulo__c/fields/Tiempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_Estimado__c</fullName>
    <label>Tiempo Estimado</label>
    <summarizedField>Unidad__c.Tiempo_Estimado__c</summarizedField>
    <summaryForeignKey>Unidad__c.Modulo__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Pregunta__c/Pregunta__c.object-meta.xml
<CustomObject>
    <label>Pregunta</label>
    <nameField>
        <label>Pregunta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preguntas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pregunta__c/fields/Contenido__c.field-meta.xml
<CustomField>
    <fullName>Contenido__c</fullName>
    <label>Contenido</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Pregunta__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidad</label>
    <referenceTo>Unidad__c</referenceTo>
    <relationshipLabel>Preguntas</relationshipLabel>
    <relationshipName>Preguntas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Respuesta__c/fields/Contenido_Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Contenido_Respuesta__c</fullName>
    <label>Contenido Respuesta</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Respuesta__c/fields/Es_Correcta__c.field-meta.xml
<CustomField>
    <fullName>Es_Correcta__c</fullName>
    <label>Es Correcto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
                <default>true</default>
                <label>Si</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Modulo__c/Trail_Modulo__c.object-meta.xml
<CustomObject>
    <label>Trail Modulo</label>
    <nameField>
        <label>Trail Modulo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trail Modulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Modulo__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Trail Modulos</relationshipLabel>
    <relationshipName>Trail_Modulos</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Modulo__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <formula>Modulo__r.Puntos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Puntos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trail_Modulo__c/fields/Tiempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_Estimado__c</fullName>
    <formula>Modulo__r.Tiempo_Estimado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tiempo Estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unidad__c/Unidad__c.object-meta.xml
<CustomObject>
    <label>Unidad</label>
    <nameField>
        <label>Unidad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unidad__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unidad__c/fields/Tiempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_Estimado__c</fullName>
    <label>Tiempo Estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Modulo__c/User_Modulo__c.object-meta.xml
<CustomObject>
    <label>User Modulo</label>
    <nameField>
        <label>User Modulo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Modulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Modulo__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <referenceTo>Modulo__c</referenceTo>
    <relationshipLabel>User Modulos</relationshipLabel>
    <relationshipName>User_Modulos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Modulo__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <summarizedField>User_Unidad__c.Puntos__c</summarizedField>
    <summaryForeignKey>User_Unidad__c.User_Modulo__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Modulo__c/fields/Tiempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_Estimado__c</fullName>
    <label>Tiempo Estimado</label>
    <summarizedField>User_Unidad__c.Tiempo_Estimado__c</summarizedField>
    <summaryForeignKey>User_Unidad__c.User_Modulo__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Modulo__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Modulos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Respuesta__c/User_Respuesta__c.object-meta.xml
<CustomObject>
    <label>User Respuesta</label>
    <nameField>
        <label>User Respuesta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Respuestas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Respuesta__c/fields/Pregunta__c.field-meta.xml
<CustomField>
    <fullName>Pregunta__c</fullName>
    <label>Pregunta</label>
    <referenceTo>Pregunta__c</referenceTo>
    <relationshipLabel>User Respuestas</relationshipLabel>
    <relationshipName>User_Respuestas1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Respuesta__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Respuesta</label>
    <referenceTo>Respuesta__c</referenceTo>
    <relationshipLabel>User Respuestas</relationshipLabel>
    <relationshipName>User_Respuestas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Respuesta__c/fields/User_Unidad__c.field-meta.xml
<CustomField>
    <fullName>User_Unidad__c</fullName>
    <label>User Unidad</label>
    <referenceTo>User_Unidad__c</referenceTo>
    <relationshipLabel>User Respuestas</relationshipLabel>
    <relationshipName>User_Respuestas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Trail__c/User_Trail__c.object-meta.xml
<CustomObject>
    <label>User Trail</label>
    <nameField>
        <label>User Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Trails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Trail__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <formula>Trail__r.Puntos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Puntos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Trail__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Trails1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unidad__c/User_Unidad__c.object-meta.xml
<CustomObject>
    <label>User Unidad</label>
    <nameField>
        <label>User Unidad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Unidad__c/fields/Tiempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tiempo_Estimado__c</fullName>
    <label>Tiempo Estimado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Unidad__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidad</label>
    <referenceTo>Unidad__c</referenceTo>
    <relationshipLabel>User Unidades</relationshipLabel>
    <relationshipName>User_Unidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unidad__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Unidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Unidad__c/fields/User_Modulo__c.field-meta.xml
<CustomField>
    <fullName>User_Modulo__c</fullName>
    <label>User Modulo</label>
    <referenceTo>User_Modulo__c</referenceTo>
    <relationshipLabel>User Unidades</relationshipLabel>
    <relationshipName>User_Unidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitServiceTest.cls
@isTest
public class UnitServiceTest {

   @isTest 
    private static void firstTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Modulo__c module = new Modulo__c(
            Name = 'PrimerModuloTest',
            Rol__c = 'Admin',
            Skill__c = 'Apex'
        );
        insert module;
        
        Unidad__c unit = new Unidad__c(
        	Modulo__c = module.id,
            Puntos__c = 100,
            Contenido__c = 'First unit content',
            Tiempo_Estimado__c = 20
        );
        insert unit;
        
        Pregunta__c question = new Pregunta__c(
            Unidad__c = unit.id,
            Contenido__c = 'Question description, the real question'
        );
        insert question;
        
        Respuesta__c option = new Respuesta__c(
            Pregunta__c = question.id,
            Contenido_Respuesta__c = 'Option descrition, the real option',
            Es_Correcta__c = 'Si'
        );
        insert option;
        
        User_Respuesta__c questionResponse = new User_Respuesta__c(
            Pregunta__c = question.id,
            Respuesta__c = option.id
        );
        insert questionResponse;

        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, option.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest(); 
        
        System.assertEquals(true, result);
        List<User_Unidad__c> unitResponses = [SELECT Id, Estados__c FROM User_Unidad__c WHERE Unidad__c = :unit.Id];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Success', unitResponses[0].Estados__c);
        
        List<User_Respuesta__c> questionResponses = [SELECT Id, Pregunta__c, Respuesta__c FROM User_Respuesta__c WHERE User_Unidad__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Pregunta__c);
        System.assertEquals(option.Id, questionResponses[0].Respuesta__c);
        
        
    }
    
        @isTest
    private static void secondTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Modulo__c module = new Modulo__c(
            Name = 'PrimerModuloTest',
            Rol__c = 'Admin',
            Skill__c = 'Apex'
        );
        insert module;
        
        Unidad__c unit = new Unidad__c(
            Modulo__c = module.id,
            Puntos__c = 100,
            Contenido__c = 'First unit content',
            Tiempo_Estimado__c = 20
        );
        insert unit;
        
        Pregunta__c question = new Pregunta__c(
            Unidad__c = unit.id,
            Contenido__c = 'Question description, the real question'
        );
        insert question;
        
        Respuesta__c option = new Respuesta__c(
            Pregunta__c = question.id,
            Contenido_Respuesta__c = 'Option descrition, the real option',
            Es_Correcta__c = 'Si'
        );
        insert option;
        
        User_Modulo__c moduleResponse = new User_Modulo__c(
            Modulo__c = module.id,
            User__c = testUser.id
        );
        insert moduleResponse;        
        
        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, option.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest();
        
        System.assertEquals(true, result);
        List<User_Unidad__c> unitResponses = [SELECT Id, Estados__c FROM User_Unidad__c];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Success', unitResponses[0].Estados__c);
        
        List<User_Respuesta__c> questionResponses = [SELECT Id, Pregunta__c, Respuesta__c FROM User_Respuesta__c WHERE User_Unidad__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Pregunta__c);
        System.assertEquals(option.Id, questionResponses[0].Respuesta__c);
    }
    
    @isTest
    private static void thirdTestMethod(){
        
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Modulo__c module = new Modulo__c(
            Name = 'PrimerModuloTest',
            Rol__c = 'Admin',
            Skill__c = 'Apex'
        );
        insert module;
        
        Unidad__c unit = new Unidad__c(
            Modulo__c = module.id,
            Puntos__c = 100,
            Contenido__c = 'First unit content',
            Tiempo_Estimado__c = 20
        );
        insert unit;
        
        Pregunta__c question = new Pregunta__c(
            Unidad__c = unit.id,
            Contenido__c = 'Question description, the real question'
        );
        insert question;
        
        Respuesta__c option = new Respuesta__c(
            Pregunta__c = question.id,
            Contenido_Respuesta__c = 'Option descrition, the real option',
            Es_Correcta__c = 'Si'
        );
        insert option;
        
        Respuesta__c wrongOption = new Respuesta__c(
            Pregunta__c = question.id,
            Contenido_Respuesta__c  = 'Option descrition, the real incorrect option',
            Es_Correcta__c = 'No'
        );
        insert wrongOption;
        
        User_Modulo__c moduleResponse = new User_Modulo__c(
            Modulo__c = module.id,
            User__c = testUser.id
        );
        insert moduleResponse;
        
        User_Respuesta__c questionResponse = new User_Respuesta__c(
            Pregunta__c = question.id,
            Respuesta__c = wrongOption.id
        );
        insert questionResponse;
        
        
        Map<Id, Id> jsonAnswers = new Map<Id, Id>();
        jsonAnswers.put(question.id, wrongOption.id);
        
        Object testAnswers = jsonAnswers;
        
        test.startTest();
        Boolean result = UnitService.saveAnswers(unit.Id, testAnswers);
        test.stopTest();
        
        System.assertEquals(true, result);
        List<User_Unidad__c> unitResponses = [SELECT Id, Estados__c FROM User_Unidad__c];
        System.assertEquals(1, unitResponses.size());
        System.assertEquals('Fail', unitResponses[0].Estados__c);
        
        List<User_Respuesta__c> questionResponses = [SELECT Id, Pregunta__c, Respuesta__c FROM User_Respuesta__c WHERE User_Unidad__c = :unitResponses[0].Id];
        System.assertEquals(1, questionResponses.size());
        System.assertEquals(question.Id, questionResponses[0].Pregunta__c);
        System.assertEquals(wrongOption.Id, questionResponses[0].Respuesta__c);
    }
    
    @isTest
    private static void wrapperTestMethod(){
        User testUser = [select Id from User where Id = :UserInfo.getUserId()];
        
        Trail__c trail = new Trail__c(
            Name = 'Primer trail',
            Detalle__c = 'Una desc'
        );
        insert trail;
        
        User_Trail__c trailProgress = new User_Trail__c(
            User__c = testUser.Id,
            Trail__c = trail.id
        );
        insert trailProgress;
        
        Modulo__c module = new Modulo__c(
            Name = 'PrimerModuloTest',
            Rol__c = 'Admin',
            Skill__c = 'Apex',
            Active__c = true
        );
        insert module;
        
        Trail_Modulo__c trailModule = new Trail_Modulo__c(
            Trail__c = trail.id,
            Modulo__c = module.id
        );
        insert trailModule;
        
        Unidad__c unit = new Unidad__c(
            Modulo__c = module.id,
            Puntos__c = 100,
            Contenido__c = 'First unit content',
            Tiempo_Estimado__c = 20
        );
        insert unit;
        
        Pregunta__c question = new Pregunta__c(
            Unidad__c = unit.id,
            Contenido__c = 'Question description, the real question'
        );
        insert question;
        
        Respuesta__c option = new Respuesta__c(
            Pregunta__c = question.id,
            Contenido_Respuesta__c = 'Option descrition, the real option',
            Es_Correcta__c = 'Si'
        );
        insert option;
        
        User_Modulo__c moduleResponse = new User_Modulo__c(
            Modulo__c = module.id,
            User__c = testUser.id,
            Estado__c = 'Completado'
        );
        insert moduleResponse;
        
        User_Unidad__c unitResponse = new User_Unidad__c(
            User_Modulo__c = moduleResponse.id,
            Unidad__c = unit.id,
            Estados__c = 'Success'
        );
        insert unitResponse;
        
        Test.startTest();
        UnitService.TrailWrapper tw = UnitService.getTrailWrapper(trail.id);
        UnitService.UnitWrapper uw = UnitService.getUnitWrapper(unit.Id);
        Test.stopTest();
        
        System.assert(tw != null);
        System.assertEquals('Primer trail', tw.trail.Name);
        System.assert(uw != null);
        
    }
    
        
}